export const JOB_TYPE = {
  CONNECT: 'Connect',
}

export const COUNTRY_CALLING_CODES = {
  US: 1,
  CA: 1,
  MX: 52,
  UK: 44,
  TZ: 255,
  AG: 213,
  AN: 376,
  AO: 244,
  AV: 1264,
  AC: 1268,
  AR: 54,
  AM: 374,
  AA: 297,
  AS: 61,
  AU: 43,
  AJ: 994,
  BF: 1242,
  BA: 973,
  BG: 880,
  BB: 1246,
  BO: 375,
  BE: 32,
  BH: 501,
  BN: 229,
  BD: 1441,
  BT: 975,
  BL: 591,
  BK: 387,
  BC: 267,
  BR: 55,
  BX: 673,
  BU: 359,
  UV: 226,
  BY: 257,
  CB: 855,
  CM: 237,
  CJ: 1345,
  CT: 236,
  CI: 56,
  CH: 86,
  CO: 57,
  CN: 269,
  CW: 682,
  CS: 506,
  HR: 385,
  CU: 53,
  EZ: 42,
  DA: 45,
  DJ: 253,
  DO: 1809,
  DR: 1809,
  EC: 593,
  EG: 20,
  ES: 503,
  EK: 240,
  ER: 291,
  EN: 372,
  ET: 251,
  FO: 298,
  FJ: 679,
  FI: 358,
  FR: 33,
  FP: 689,
  GB: 241,
  GA: 220,
  GG: 7880,
  GM: 49,
  GH: 233,
  GI: 350,
  GR: 30,
  GL: 299,
  GJ: 1473,
  GT: 502,
  GV: 224,
  PU: 245,
  GY: 592,
  HA: 509,
  HO: 504,
  HK: 852,
  HU: 36,
  IC: 354,
  IN: 91,
  ID: 62,
  IR: 98,
  IZ: 964,
  EI: 353,
  IS: 972,
  IT: 39,
  JM: 1876,
  JA: 81,
  JO: 962,
  KZ: 7,
  KE: 254,
  KR: 686,
  KN: 850,
  KS: 82,
  KU: 965,
  KG: 996,
  LA: 856,
  LG: 371,
  LE: 961,
  LT: 266,
  LI: 231,
  LY: 218,
  LS: 417,
  LH: 370,
  LU: 352,
  MK: 389,
  MA: 261,
  MI: 265,
  MY: 60,
  MV: 960,
  ML: 223,
  MT: 356,
  RM: 692,
  MR: 222,
  MF: 269,
  FM: 691,
  MD: 373,
  MN: 377,
  MG: 976,
  MH: 1664,
  MO: 212,
  MZ: 258,
  WA: 264,
  NR: 674,
  NP: 977,
  NL: 31,
  NC: 687,
  NZ: 64,
  NU: 505,
  NG: 227,
  NI: 234,
  NE: 683,
  NO: 47,
  MU: 968,
  PS: 680,
  PM: 507,
  PP: 675,
  PA: 595,
  PE: 51,
  RP: 63,
  PL: 48,
  PO: 351,
  QA: 974,
  RO: 40,
  RS: 7,
  RW: 250,
  SM: 378,
  TP: 239,
  SA: 966,
  SG: 221,
  RB: 381,
  SE: 248,
  SL: 232,
  SN: 65,
  SI: 386,
  BP: 677,
  SO: 252,
  SF: 27,
  SP: 34,
  CE: 94,
  SU: 249,
  NS: 597,
  WZ: 268,
  SW: 46,
  SZ: 41,
  SY: 963,
  TW: 886,
  TH: 66,
  TO: 228,
  TN: 676,
  TD: 1868,
  TS: 216,
  TU: 90,
  TX: 7,
  // TX: 993,
  TK: 1649,
  TV: 688,
  UG: 256,
  UP: 380,
  AE: 971,
  UY: 598,
  UZ: 7,
  NH: 678,
  VE: 58,
  VM: 84,
  VI: 1284,
  WF: 681,
  YM: 969,
  // YM: 967,
  ZA: 260,
  ZI: 263,
}

export const COUNTRIES = {
  US: 'UNITED STATES',
  CA: 'CANADA',
  MX: 'MEXICO',
  AF: 'AFGHANISTAN',
  AX: 'AKROTIRI SOVEREIGN BASE AREA',
  AL: 'ALBANIA',
  AG: 'ALGERIA',
  AN: 'ANDORRA',
  AO: 'ANGOLA',
  AV: 'ANGUILLA',
  AY: 'ANTARCTICA',
  AC: 'ANTIGUA AND BARBUDA',
  AR: 'ARGENTINA',
  AM: 'ARMENIA',
  AA: 'ARUBA',
  AT: 'ASHMORE AND CARTIER ISLANDS',
  AS: 'AUSTRALIA',
  AU: 'AUSTRIA',
  AJ: 'AZERBAIJAN',
  BF: 'BAHAMAS',
  BA: 'BAHRAIN',
  FQ: 'BAKER ISLAND',
  BG: 'BANGLADESH',
  BB: 'BARBADOS',
  BO: 'BELARUS',
  BE: 'BELGIUM',
  BH: 'BELIZE',
  BN: 'BENIN',
  BD: 'BERMUDA',
  BT: 'BHUTAN',
  BL: 'BOLIVIA',
  BK: 'BOSNIA AND HERZEGOVINA',
  BC: 'BOTSWANA',
  BV: 'BOUVET ISLAND',
  BR: 'BRAZIL',
  IO: 'BRITISH INDIAN OCEAN TERRITORY',
  BX: 'BRUNEI',
  BU: 'BULGARIA',
  UV: 'BURKINA FASO',
  BM: 'BURMA',
  BY: 'BURUNDI',
  CB: 'CAMBODIA',
  CM: 'CAMEROON',
  CV: 'CAPE VERDE',
  CJ: 'CAYMAN ISLANDS',
  CT: 'CENTRAL AFRICAN REPUBLIC',
  CD: 'CHAD',
  CI: 'CHILE',
  CH: 'CHINA',
  KT: 'CHRISTMAS ISLAND',
  IP: 'CLIPPERTON ISLAND',
  CK: 'COCOS KEELING ISLANDS',
  CO: 'COLOMBIA',
  CN: 'COMOROS',
  CF: 'CONGO BRAZZAVILLE',
  CG: 'CONGO KINSHASA',
  CW: 'COOK ISLANDS',
  CR: 'CORAL SEA ISLANDS',
  CS: 'COSTA RICA',
  IV: 'COTE D IVOIRE',
  HR: 'CROATIA',
  CU: 'CUBA',
  CY: 'CYPRUS',
  EZ: 'CZECH REPUBLIC',
  DA: 'DENMARK',
  DX: 'DHEKELIA SOVEREIGN BASE AREA',
  DJ: 'DJIBOUTI',
  DO: 'DOMINICA',
  DR: 'DOMINICAN REPUBLIC',
  TT: 'EAST TIMOR',
  EC: 'ECUADOR',
  EG: 'EGYPT',
  ES: 'EL SALVADOR',
  EK: 'EQUATORIAL GUINEA',
  ER: 'ERITREA',
  EN: 'ESTONIA',
  ET: 'ETHIOPIA',
  FK: 'FALKLAND ISLANDS ISLAS MALVINAS',
  FO: 'FAROE ISLANDS',
  FJ: 'FIJI',
  FI: 'FINLAND',
  FR: 'FRANCE',
  FP: 'FRENCH POLYNESIA',
  FS: 'FRENCH SOUTHERN AND ANTARCTIC LANDS',
  GB: 'GABON',
  GA: 'GAMBIA',
  GG: 'GEORGIA',
  GM: 'GERMANY',
  GH: 'GHANA',
  GI: 'GIBRALTAR',
  GR: 'GREECE',
  GL: 'GREENLAND',
  GJ: 'GRENADA',
  GT: 'GUATEMALA',
  GK: 'GUERNSEY',
  GV: 'GUINEA',
  PU: 'GUINEA BISSAU',
  GY: 'GUYANA',
  HA: 'HAITI',
  HM: 'HEARD ISLAND AND MCDONALD ISLANDS',
  VT: 'HOLY SEE',
  HO: 'HONDURAS',
  HK: 'HONG KONG',
  HQ: 'HOWLAND ISLAND',
  HU: 'HUNGARY',
  IC: 'ICELAND',
  IN: 'INDIA',
  ID: 'INDONESIA',
  IR: 'IRAN',
  IZ: 'IRAQ',
  EI: 'IRELAND',
  IM: 'ISLE OF MAN',
  IS: 'ISRAEL',
  IT: 'ITALY',
  JM: 'JAMAICA',
  JN: 'JAN MAYEN',
  JA: 'JAPAN',
  DQ: 'JARVIS ISLAND',
  JE: 'JERSEY',
  JQ: 'JOHNSTON ATOLL',
  JO: 'JORDAN',
  KZ: 'KAZAKHSTAN',
  KE: 'KENYA',
  KQ: 'KINGMAN REEF',
  KR: 'KIRIBATI',
  KN: 'KOREA NORTH',
  KS: 'KOREA SOUTH',
  KU: 'KUWAIT',
  KG: 'KYRGYZSTAN',
  LA: 'LAOS',
  LG: 'LATVIA',
  LE: 'LEBANON',
  LT: 'LESOTHO',
  LI: 'LIBERIA',
  LY: 'LIBYA',
  LS: 'LIECHTENSTEIN',
  LH: 'LITHUANIA',
  LU: 'LUXEMBOURG',
  MC: 'MACAU',
  MK: 'MACEDONIA',
  MA: 'MADAGASCAR',
  MI: 'MALAWI',
  MY: 'MALAYSIA',
  MV: 'MALDIVES',
  ML: 'MALI',
  MT: 'MALTA',
  RM: 'MARSHALL ISLANDS',
  MR: 'MAURITANIA',
  MP: 'MAURITIUS',
  MF: 'MAYOTTE',
  FM: 'MICRONESIA FEDERATED STATES OF',
  MQ: 'MIDWAY ISLANDS',
  MD: 'MOLDOVA',
  MN: 'MONACO',
  MG: 'MONGOLIA',
  MJ: 'MONTENEGRO',
  MH: 'MONTSERRAT',
  MO: 'MOROCCO',
  MZ: 'MOZAMBIQUE',
  WA: 'NAMIBIA',
  NR: 'NAURU',
  BQ: 'NAVASSA ISLAND',
  NP: 'NEPAL',
  NL: 'NETHERLANDS',
  NT: 'NETHERLANDS ANTILLES',
  NC: 'NEW CALEDONIA',
  NZ: 'NEW ZEALAND',
  NU: 'NICARAGUA',
  NG: 'NIGER',
  NI: 'NIGERIA',
  NE: 'NIUE',
  NF: 'NORFOLK ISLAND',
  CQ: 'NORTHERN MARIANA ISLANDS',
  NO: 'NORWAY',
  MU: 'OMAN',
  PK: 'PAKISTAN',
  PS: 'PALAU',
  LQ: 'PALMYRA ATOLL',
  PM: 'PANAMA',
  PP: 'PAPUA NEW GUINEA',
  PF: 'PARACEL ISLANDS',
  PA: 'PARAGUAY',
  PE: 'PERU',
  RP: 'PHILIPPINES',
  PC: 'PITCAIRN ISLANDS',
  PL: 'POLAND',
  PO: 'PORTUGAL',
  QA: 'QATAR',
  RO: 'ROMANIA',
  RS: 'RUSSIA',
  RW: 'RWANDA',
  SH: 'SAINT HELENA',
  SC: 'SAINT KITTS AND NEVIS',
  ST: 'SAINT LUCIA',
  SB: 'SAINT PIERRE AND MIQUELON',
  VC: 'SAINT VINCENT AND GRENADINES',
  WS: 'SAMOA',
  SM: 'SAN MARINO',
  TP: 'SAO TOME AND PRINCIPE',
  SA: 'SAUDI ARABIA',
  SG: 'SENEGAL',
  RB: 'SERBIA',
  SE: 'SEYCHELLES',
  SL: 'SIERRA LEONE',
  SN: 'SINGAPORE',
  LO: 'SLOVAKIA',
  SI: 'SLOVENIA',
  BP: 'SOLOMON ISLANDS',
  SO: 'SOMALIA',
  SF: 'SOUTH AFRICA',
  SX: 'SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS',
  SP: 'SPAIN',
  PG: 'SPRATLY ISLANDS',
  CE: 'SRI LANKA',
  SU: 'SUDAN',
  NS: 'SURINAME',
  SV: 'SVALBARD',
  WZ: 'SWAZILAND',
  SW: 'SWEDEN',
  SZ: 'SWITZERLAND',
  SY: 'SYRIA',
  TW: 'TAIWAN',
  TI: 'TAJIKISTAN',
  TZ: 'TANZANIA',
  TH: 'THAILAND',
  TO: 'TOGO',
  TL: 'TOKELAU',
  TN: 'TONGA',
  TD: 'TRINIDAD AND TOBAGO',
  TS: 'TUNISIA',
  TU: 'TURKEY',
  TX: 'TURKMENISTAN',
  TK: 'TURKS AND CAICOS ISLANDS',
  TV: 'TUVALU',
  UG: 'UGANDA',
  UP: 'UKRAINE',
  AE: 'UNITED ARAB EMIRATES',
  UK: 'UNITED KINGDOM',
  UY: 'URUGUAY',
  UZ: 'UZBEKISTAN',
  NH: 'VANUATU',
  VE: 'VENEZUELA',
  VM: 'VIETNAM',
  WQ: 'WAKE ISLAND',
  WF: 'WALLIS AND FUTUNA',
  WI: 'WESTERN SAHARA',
  YM: 'YEMEN',
  ZA: 'ZAMBIA',
  ZI: 'ZIMBABWE',
}

/**
 * Get an array of countries with names formatted to DHS website
 */
export const COUNTRIES_ALT = {
  AF: 'AFGHANISTAN',
  AL: 'ALBANIA',
  AG: 'ALGERIA',
  AN: 'ANDORRA',
  AO: 'ANGOLA',
  AV: 'ANGUILLA',
  AC: 'ANTIGUA AND BARBUDA',
  AR: 'ARGENTINA',
  AM: 'ARMENIA',
  AA: 'ARUBA',
  AS: 'AUSTRALIA',
  AU: 'AUSTRIA',
  AJ: 'AZERBAIJAN',
  BF: 'BAHAMAS',
  BA: 'BAHRAIN',
  BG: 'BANGLADESH',
  BB: 'BARBADOS',
  BO: 'BELARUS',
  BE: 'BELGIUM',
  BH: 'BELIZE',
  BN: 'BENIN',
  BD: 'BERMUDA',
  BT: 'BHUTAN',
  BL: 'BOLIVIA',
  BK: 'BOSNIA AND HERZEGOVINA',
  BC: 'BOTSWANA',
  BR: 'BRAZIL',
  BX: 'BRUNEI DARUSSALAM',
  BU: 'BULGARIA',
  UV: 'BURKINA FASO',
  BM: 'BURMA',
  BY: 'BURUNDI',
  CB: 'CAMBODIA',
  CM: 'CAMEROON',
  CV: 'CAPE VERDE',
  CJ: 'CAYMAN ISLANDS',
  CT: 'CENTRAL AFRICAN REPUBLIC',
  CD: 'CHAD',
  CI: 'CHILE',
  CH: 'CHINA',
  CO: 'COLOMBIA',
  CF: 'CONGO',
  CG: 'DEMOCRATIC REPUBLIC OF THE CONGO',
  CW: 'COOK ISLANDS',
  CS: 'COSTA RICA',
  IV: "COTE D'IVOIRE",
  HR: 'CROATIA',
  CU: 'CUBA',
  CY: 'CYPRUS',
  EZ: 'CZECH REPUBLIC',
  DA: 'DENMARK',
  DJ: 'DJIBOUTI',
  DO: 'DOMINICA',
  DR: 'DOMINICAN REPUBLIC',
  TT: 'EAST TIMOR',
  EC: 'ECUADOR',
  EG: 'EGYPT',
  ES: 'EL SALVADOR',
  EK: 'EQUATORIAL GUINEA',
  ER: 'ERITREA',
  EN: 'ESTONIA',
  ET: 'ETHIOPIA',
  FJ: 'FIJI',
  FI: 'FINLAND',
  FR: 'FRANCE',
  FP: 'FRENCH POLYNESIA',
  GB: 'GABON',
  GA: 'GAMBIA',
  GG: 'GEORGIA',
  GM: 'GERMANY',
  GH: 'GHANA',
  GR: 'GREECE',
  GJ: 'GRENADA',
  GT: 'GUATEMALA',
  GK: 'GUERNSEY',
  GV: 'GUINEA',
  PU: 'GUINEA-BISSAU',
  GY: 'GUYANA',
  HA: 'HAITI',
  HO: 'HONDURAS',
  HK: 'HONG KONG',
  HU: 'HUNGARY',
  IC: 'ICELAND',
  IN: 'INDIA',
  ID: 'INDONESIA',
  IR: 'IRAN (ISLAMIC REPUBLIC OF)',
  IZ: 'IRAQ',
  EI: 'IRELAND',
  IM: 'ISLE OF MAN',
  IS: 'ISRAEL',
  IT: 'ITALY',
  JM: 'JAMAICA',
  JA: 'JAPAN',
  JE: 'JERSEY',
  JO: 'JORDAN',
  KZ: 'KAZAKHSTAN',
  KE: 'KENYA',
  KR: 'KIRIBATI',
  KN: "KOREA - DEMOCRATIC PEOPLE'S REPUBLIC OF",
  KS: 'KOREA - REPUBLIC OF',
  KU: 'KUWAIT',
  KG: 'KYRGYZSTAN',
  LA: 'LAOS',
  LG: 'LATVIA',
  LE: 'LEBANON',
  LT: 'LESOTHO',
  LI: 'LIBERIA',
  LY: 'LIBYA',
  LS: 'LIECHTENSTEIN',
  LH: 'LITHUANIA',
  LU: 'LUXEMBOURG',
  MK: 'MACEDONIA',
  MA: 'MADAGASCAR',
  MI: 'MALAWI',
  MY: 'MALAYSIA',
  MV: 'MALDIVES',
  ML: 'MALI',
  MT: 'MALTA',
  RM: 'MARSHALL ISLANDS',
  MR: 'MAURITANIA',
  MP: 'MAURITIUS',
  FM: 'MICRONESIA - FEDERATED STATES OF',
  MD: 'MOLDOVA - REPUBLIC OF',
  MN: 'MONACO',
  MG: 'MONGOLIA',
  MJ: 'MONTENEGRO',
  MH: 'MONTSERRAT',
  MO: 'MOROCCO',
  MZ: 'MOZAMBIQUE',
  WA: 'NAMIBIA',
  NR: 'NAURU',
  NP: 'NEPAL',
  NL: 'NETHERLANDS',
  NT: 'NETHERLANDS ANTILLES',
  NC: 'NEW CALEDONIA',
  NZ: 'NEW ZEALAND',
  NU: 'NICARAGUA',
  NG: 'NIGER',
  NI: 'NIGERIA',
  NE: 'NIUE',
  NO: 'NORWAY',
  MU: 'OMAN',
  PK: 'PAKISTAN',
  PS: 'PALAU',
  PM: 'PANAMA',
  PP: 'PAPUA NEW GUINEA',
  PA: 'PARAGUAY',
  PE: 'PERU',
  RP: 'PHILIPPINES',
  PC: 'PITCAIRN',
  PL: 'POLAND',
  PO: 'PORTUGAL',
  QA: 'QATAR',
  RO: 'ROMANIA',
  RS: 'RUSSIAN FEDERATION',
  RW: 'RWANDA',
  SC: 'SAINT KITTS AND NEVIS',
  ST: 'SAINT LUCIA',
  VC: 'SAINT VINCENT AND THE GRENADINES',
  WS: 'SAMOA',
  SM: 'SAN MARINO',
  TP: 'SAO TOME AND PRINCIPE',
  SA: 'SAUDI ARABIA',
  SG: 'SENEGAL',
  RB: 'SERBIA',
  SE: 'SEYCHELLES',
  SL: 'SIERRA LEONE',
  SN: 'SINGAPORE',
  SI: 'SLOVENIA',
  LO: 'SLOVAKIA (Slovak Republic)',
  BP: 'SOLOMON ISLANDS',
  SO: 'SOMALIA',
  SF: 'SOUTH AFRICA',
  SP: 'SPAIN',
  CE: 'SRI LANKA',
  SU: 'SUDAN',
  NS: 'SURINAME',
  WZ: 'SWAZILAND',
  SW: 'SWEDEN',
  SZ: 'SWITZERLAND',
  SY: 'SYRIA',
  TW: 'TAIWAN',
  TI: 'TAJIKISTAN',
  TZ: 'TANZANIA - UNITED REPUBLIC OF',
  TH: 'THAILAND',
  TO: 'TOGO',
  TN: 'TONGA',
  TD: 'TRINIDAD AND TOBAGO',
  TS: 'TUNISIA',
  TU: 'TURKEY',
  TX: 'TURKMENISTAN',
  TK: 'TURKS AND CAICOS ISLANDS',
  TV: 'TUVALU',
  UG: 'UGANDA',
  UP: 'UKRAINE',
  CN: 'UNION OF THE COMOROS',
  AE: 'UNITED ARAB EMIRATES',
  UK: 'UNITED KINGDOM',
  UY: 'URUGUAY',
  UZ: 'UZBEKISTAN',
  NH: 'VANUATU',
  VE: 'VENEZUELA',
  VM: 'VIETNAM',
  YM: 'YEMEN',
  ZA: 'ZAMBIA',
  ZI: 'ZIMBABWE',
}

export const STATES = {
  AL: 'Alabama',
  AK: 'Alaska',
  AZ: 'Arizona',
  AR: 'Arkansas',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  DC: 'District Of Columbia',
  FL: 'Florida',
  GA: 'Georgia',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VT: 'Vermont',
  VA: 'Virginia',
  WA: 'Washington',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming',
  AS: 'American Samoa',
  FM: 'Federated States Of Micronesia',
  GU: 'Guam',
  MH: 'Marshall Islands',
  MP: 'Northern Mariana Islands',
  PW: 'Palau',
  PR: 'Puerto Rico',
  VI: 'Virgin Islands',
  AE: 'Armed Forces Africa',
  AA: 'Armed Forces Americas',
  // AE: 'Armed Forces Canada',
  // AE: 'Armed Forces Europe',
  // AE: 'Armed Forces Middle East',
  AP: 'Armed Forces Pacific',
}

export const CANANDIAN_STATES = {
  AB: 'Alberta',
  BC: 'British Columbia',
  MB: 'Manitoba',
  NB: 'New Brunswick',
  NL: 'Newfoundland and Labrador',
  NT: 'Northwest Territories',
  NS: 'Nova Scotia',
  NU: 'Nunavut',
  ON: 'Ontario',
  PE: 'Prince Edward Island',
  QC: 'Quebec',
  SK: 'Saskatchewan',
  YT: 'Yukon',
}

export const MEXICAN_STATES = {
  AGU: 'Aguascalientes',
  BCN: 'Baja California',
  BCS: 'Baja California Sur',
  CAM: 'Campeche',
  CHP: 'Chiapas',
  CHH: 'Chihuahua',
  COA: 'Coahuila',
  COL: 'Colima',
  DIF: 'Distrito Federal',
  CMX: 'Mexico City',
  DUR: 'Durango',
  GUA: 'Guanajuato',
  GRO: 'Guerrero',
  HID: 'Hidalgo',
  JAL: 'Jalisco',
  MEX: 'Mexico',
  MIC: 'Michoacan',
  MOR: 'Morelos',
  NAY: 'Nayarit',
  NLE: 'Nuevo Leon',
  OAX: 'Oaxaca',
  PUE: 'Puebla',
  QUE: 'Queretaro',
  ROO: 'Quintana Roo',
  SLP: 'San Luis Potosi',
  SIN: 'Sinaloa',
  SON: 'Sonora',
  TAB: 'Tabasco',
  TAM: 'Tamaulipas',
  TLA: 'Tlaxcala',
  VER: 'Veracruz',
  YUC: 'Yucatan',
  ZAC: 'Zacatecas',
}

export const MONTHS: Record<number, string> = {
  1: 'january',
  2: 'february',
  3: 'march',
  4: 'april',
  5: 'may',
  6: 'june',
  7: 'july',
  8: 'august',
  9: 'september',
  10: 'october',
  11: 'november',
  12: 'december',
}

export const UNWANTED_CHARS: { [key: string]: string } = {
  Š: 'S',
  š: 's',
  Ž: 'Z',
  ž: 'z',
  À: 'A',
  Á: 'A',
  Â: 'A',
  Ã: 'A',
  Ä: 'A',
  Å: 'A',
  Æ: 'A',
  Ç: 'C',
  È: 'E',
  É: 'E',
  Ê: 'E',
  Ë: 'E',
  Ì: 'I',
  Í: 'I',
  Î: 'I',
  Ï: 'I',
  Ñ: 'N',
  Ò: 'O',
  Ó: 'O',
  Ô: 'O',
  Õ: 'O',
  Ö: 'O',
  Ø: 'O',
  Ù: 'U',
  Ú: 'U',
  Û: 'U',
  Ü: 'U',
  Ý: 'Y',
  Þ: 'B',
  ß: 'Ss',
  à: 'a',
  á: 'a',
  â: 'a',
  ã: 'a',
  ä: 'a',
  å: 'a',
  æ: 'a',
  ç: 'c',
  è: 'e',
  é: 'e',
  ê: 'e',
  ë: 'e',
  ì: 'i',
  í: 'i',
  î: 'i',
  ï: 'i',
  ð: 'o',
  ñ: 'n',
  ò: 'o',
  ó: 'o',
  ô: 'o',
  õ: 'o',
  ö: 'o',
  ø: 'o',
  ù: 'u',
  ú: 'u',
  û: 'u',
  ý: 'y',
  þ: 'b',
  ÿ: 'y',
}

export const STATUSES: { [key: number]: string } = {
  0: 'In Progress',
  9: 'Issues',
  7: 'Ready for Payment',
  6: 'Submitted',
  1: 'Completed',
  8: 'Customer Took Over',
  2: 'Refunded',
  3: 'Chargeback',
  4: 'Refunded - Sent to Collections',
  5: 'Refunded - Collected',
  10: 'Unresponsive',
}

export const ISSUES: { [key: number]: string } = {
  0: 'n/a',
  1: 'Waiting for Refund',
  2: 'Payment Issue',
  3: 'Incorrect PassID',
  4: 'Incomplete Information',
  5: 'Incorrect Passport Number',
  6: 'Renewing Too Early (Will Wait)',
  7: 'Renewing Too Early (No Response)',
  99: 'Other (Add a note)',
}

export const PAGE_ERRORS: { [key: string]: string } = {
  // Path segment cases
  'drivers-license': "Driver's License page issue",
  documents: 'Passport page issue',
  'vehicle-info': 'Vehicle page issue',
  'address-history': 'Addresses page issue',
  'employment-history': 'Employment page issue',
  'travel-history': 'Travel History page issue',
  'additional-info': 'Additional Info page issue',
  'final-review': 'Final Review page issue',
  'program-certification': 'Certification/Agreement page issue',

  // Full URL cases
  'https://ttp.cbp.dhs.gov/': 'Start page issue',
  'https://ttp.cbp.dhs.gov/dashboard': 'Start page issue',
  'https://secure.login.gov/login/two_factor/authenticator':
    '2 Factor Auth page issue',
  'https://ttp.cbp.dhs.gov/getstarted;stepDone=3': 'Next Steps page issue',
  'https://ttp.cbp.dhs.gov/program-selection/select-program':
    'Select Program page issue',
  'https://ttp.cbp.dhs.gov/program-selection/acknowledge':
    'Program Selection Acknowledgement page issue',
  'https://ttp.cbp.dhs.gov/purchase-summary': 'Purchase Summary page issue',
  'https://www.pay.gov/tcsonline/payment.do?execution=e1s1':
    'Payment Method page issue',
  'https://www.pay.gov/tcsonline/payment.do?execution=e1s2':
    'Payment page issue',
  'https://www.pay.gov/tcsonline/payment.do?execution=e1s3':
    'Payment Confirmation page issue',
}

export const END_EXECUTION_REASONS: Record<string, number> = {
  'birthplace-mismatch': 4,
  'dob-mismatch': 4,
  'name-mismatch': 4,
  'incorrect-passport': 5,
  'wrong-passid': 3,
  'verify-address': 4,
}

export const COUNTRIES_3_LETTERCODES = {
  US: 'USA',
  CA: 'CAN',
  AF: 'AFG',
  AL: 'ALB',
  AG: 'DZA',
  AN: 'AND',
  AO: 'AGO',
  AV: 'AIA',
  AC: 'ATG',
  AR: 'ARG',
  AM: 'ARM',
  AA: 'ABW',
  AS: 'AUS',
  AU: 'AUT',
  AJ: 'AZE',
  BF: 'BHS',
  BA: 'BHR',
  BG: 'BGD',
  BB: 'BRB',
  BO: 'BLR',
  BE: 'BEL',
  BH: 'BLZ',
  BN: 'BEN',
  BD: 'BMU',
  BT: 'BTN',
  BL: 'BOL',
  BK: 'BIH',
  BC: 'BWA',
  BR: 'BRA',
  BU: 'BGR',
  UV: 'BFA',
  BY: 'BDI',
  CB: 'KHM',
  CM: 'CMR',
  CV: 'CPV',
  CJ: 'CYM',
  CT: 'CAF',
  CD: 'TCD',
  CI: 'CHL',
  CH: 'CHN',
  CO: 'COL',
  CN: 'COM',
  CW: 'COK',
  CS: 'CRI',
  HR: 'HRV',
  CU: 'CUB',
  CY: 'CYP',
  EZ: 'CZE',
  DA: 'DNK',
  DJ: 'DJI',
  DO: 'DMA',
  DR: 'DOM',
  EC: 'ECU',
  EG: 'EGY',
  ES: 'SLV',
  EK: 'GNQ',
  ER: 'ERI',
  EN: 'EST',
  ET: 'ETH',
  FO: 'FRO',
  FJ: 'FJI',
  FI: 'FIN',
  FR: 'FRA',
  FP: 'PYF',
  GB: 'GAB',
  GA: 'GMB',
  GG: 'GEO',
  GM: 'DEU',
  GH: 'GHA',
  GI: 'GIB',
  GR: 'GRC',
  GL: 'GRL',
  GJ: 'GRD',
  GT: 'GTM',
  GK: 'GGY',
  GV: 'GIN',
  PU: 'GNB',
  GY: 'GUY',
  HA: 'HTI',
  HO: 'HND',
  HK: 'HKG',
  HU: 'HUN',
  IC: 'ISL',
  IN: 'IND',
  ID: 'IDN',
  IZ: 'IRQ',
  EI: 'IRL',
  IM: 'IMN',
  IS: 'ISR',
  IT: 'ITA',
  JM: 'JAM',
  JA: 'JPN',
  JE: 'JEY',
  JO: 'JOR',
  KZ: 'KAZ',
  KE: 'KEN',
  KR: 'KIR',
  KU: 'KWT',
  KG: 'KGZ',
  LG: 'LVA',
  LE: 'LBN',
  LT: 'LSO',
  LI: 'LBR',
  LY: 'LBY',
  LS: 'LIE',
  LH: 'LTU',
  LU: 'LUX',
  MK: 'MKD',
  MA: 'MDG',
  MI: 'MWI',
  MY: 'MYS',
  MV: 'MDV',
  ML: 'MLI',
  MT: 'MLT',
  RM: 'MHL',
  MR: 'MRT',
  MP: 'MUS',
  MF: 'MYT',
  MX: 'MEX',
  MD: 'MDA',
  MN: 'MCO',
  MG: 'MNG',
  MJ: 'MNE',
  MH: 'MSR',
  MO: 'MAR',
  MZ: 'MOZ',
  WA: 'NAM',
  NR: 'NRU',
  NP: 'NPL',
  NL: 'NLD',
  NT: 'ANT',
  NC: 'NCL',
  NZ: 'NZL',
  NU: 'NIC',
  NG: 'NER',
  NI: 'NGA',
  NE: 'NIU',
  NF: 'NFK',
  CQ: 'MNP',
  NO: 'NOR',
  MU: 'OMN',
  PK: 'PAK',
  PS: 'PLW',
  PM: 'PAN',
  PP: 'PNG',
  PA: 'PRY',
  PE: 'PER',
  RP: 'PHL',
  PL: 'POL',
  PO: 'PRT',
  QA: 'QAT',
  RO: 'ROU',
  RW: 'RWA',
  SH: 'SHN',
  SC: 'KNA',
  ST: 'LCA',
  SB: 'SPM',
  WS: 'WSM',
  SM: 'SMR',
  TP: 'STP',
  SA: 'SAU',
  SG: 'SEN',
  RB: 'SRB',
  SE: 'SYC',
  SL: 'SLE',
  SN: 'SGP',
  LO: 'SVK',
  SI: 'SVN',
  BP: 'SLB',
  SO: 'SOM',
  SF: 'ZAF',
  SP: 'ESP',
  CE: 'LKA',
  NS: 'SUR',
  WZ: 'SWZ',
  SW: 'SWE',
  SZ: 'CHE',
  TW: 'TWN',
  TI: 'TJK',
  TZ: 'TZA',
  TH: 'THA',
  TO: 'TGO',
  TL: 'TKL',
  TN: 'TON',
  TD: 'TTO',
  TS: 'TUN',
  TU: 'TUR',
  TX: 'TKM',
  TK: 'TCA',
  TV: 'TUV',
  UG: 'UGA',
  UP: 'UKR',
  AE: 'ARE',
  UK: 'GBR',
  UY: 'URY',
  UZ: 'UZB',
  NH: 'VUT',
  VE: 'VEN',
  VM: 'VNM',
  WI: 'ESH',
  YM: 'YEM',
  ZA: 'ZMB',
  ZI: 'ZWE',
  VI: 'VGB',
  BX: 'BRN',
  CF: 'COG',
  CG: 'COD',
  IV: 'CIV',
  FK: 'FLK',
  KN: 'PRK',
  KS: 'KOR',
  LA: 'LAO',
  FM: 'FSM',
  PC: 'PCN',
  RS: 'RUS',
  VC: 'VCT',
  SY: 'SYR',
  WF: 'WLF',
}

export const BUSINESS_NAMES = {
  'Global Entry': 'ge',
  NEXUS: 'nexus',
  SENTRI: 'sentri',
  'TSA Pre-Check': 'pretsa',
}
