export enum OrderStatus {
    IN_PROGRESS = 0,
    COMPLETED = 1,
    REFUNDED = 2,
    CHARGEBACK = 3,
    REFUNDED_SENT_TO_COLLECTIONS = 4,
    REFUNDED_COLLECTED = 5,
    SUBMITTED = 6,
    READY_FOR_PAYMENT = 7,
    CUSTOMER_TOOK_OVER = 8,
    ISSUES = 9,
    UNRESPONSIVE = 10,
    INTERVIEW_SCHEDULED = 11,
    INTERVIEW_MISSED = 12,
  }
  
  export enum OrderType {
    GLOBAL_ENTRY_NEW_APPLICATION = 0,
    GLOBAL_ENTRY_RENEWAL = 1,
    GLOBAL_ENTRY_CHILD_NEW = 2,
    GLOBAL_ENTRY_CHILD_RENEWAL = 3,
    NEXUS_NEW_APPLICATION = 4,
    NEXUS_RENEWAL = 5,
    NEXUS_CHILD_NEW = 6,
    NEXUS_CHILD_RENEWAL = 7,
    SENTRI_NEW_APPLICATION = 8,
    SENTRI_RENEWAL = 9,
    SENTRI_CHILD_NEW = 10,
    SENTRI_CHILD_RENEWAL = 11,
  }
  